#!/usr/bin/env python

# Python standard library.
import array
import multiprocessing
import optparse
import os
import shutil
import sys

# Our own libraries.
from Treemaker.Treemaker import core
from Treemaker.Treemaker import plugins

# Used so trees from multiple versions do not get hadd'd together.
version = "0.2beta"

def main():
	parser = optparse.OptionParser()
	parser.add_option("-c", "--config", dest="config", help="The name of the config file containing all plugin names.", default="")
	parser.add_option("-d", "--data", dest="data", action="store_true", help="If true, we are running on data.")
	parser.add_option("-f", "--force", dest="force", action="store_true", help="If true, delete things and overwrite things.")
	parser.add_option("-l", "--linear", dest="linear", action="store_true", help="If true, disable multiprocessing.")
	parser.add_option("-n", "--name", dest="name", help="The name of the output file, defaults to directory name of ntuples.", default="")
	parser.add_option("-t", "--treename", dest="treename", help="The name of the output TTree object.", default="tree-" + version)
	(opts, args) = parser.parse_args()
	
	# Attempt to load plugins from plugin config file.
	pluginNames = []
	try:
		if opts.config == "":
			raise RuntimeError
		with open(opts.config) as configFile:
			for line in configFile:
				if not line[0] == "#" and not line.lstrip().rstrip() == "":
					pluginNames.append(line)
	except RuntimeError:
		print "ERROR: attempted to run Treemaker without specifying plugins!"
		print "The safest thing to do is fail."
		print "Please rerun Treemaker with the -c [config name] option, where [config name]"
		print "is a file containing newline-separated list of plugin names."
		sys.exit(1)
	
	# Load plugins.
	plugins.loadPlugins(pluginNames)

	# Run the treemaker over all provided directories.
	for arg in args:
		directory = os.path.abspath(arg)
		if not os.path.exists(directory):
			print "Error: no such directory: " + arg
			sys.exit(1)
		core.runTreemaker(directory, opts.treename, opts.data, opts.force, opts.name, opts.linear)

if __name__ == '__main__':
	main()
