#!/usr/bin/env python

from Treemaker.Treemaker import config
from Treemaker.Treemaker import parser

def main():
	treeParser = parser.getConfigParser()
	(opts, args) = treeParser.parse_args()
	
	for arg in args:
		config.writeConfigFile(arg, opts)

if __name__ == '__main__':
	main()