#!/usr/bin/env python

# Helper script that only prints out the cut report.

# Python standard library.
import array
import multiprocessing
import optparse
import os
import shutil
import sys

# Our own libraries.
from Treemaker.Treemaker import config
from Treemaker.Treemaker import cuts
from Treemaker.Treemaker import parser
from Treemaker.Treemaker import plugins

def main():
	treeParser = parser.getCLIParser()
	(opts, args) = treeParser.parse_args()
	
	# The only positional argument treemaker v3 takes is config file.
	for arg in args:
		treemakerConfig = config.TreemakerConfig(arg)
		plugins.loadPlugins(treemakerConfig.pluginNames)
		print "Cuts that will be generated for config file " + arg + ":"
		cuts.writeCutsReport(plugins)


if __name__ == '__main__':
	main()
