#!/usr/bin/env python

# Python standard library.
import array
import multiprocessing
import optparse
import os
import shutil
import sys

# Our own libraries.
from Treemaker.Treemaker import core
from Treemaker.Treemaker import plugins

# Used so trees from multiple versions do not get hadd'd together.
version = "0.2beta"

def main():
	parser = optparse.OptionParser()
	parser.add_option("-d", "--data", dest="data", action="store_true", help="If true, we are running on data.")
	parser.add_option("-f", "--force", dest="force", action="store_true", help="If true, delete things and overwrite things.")
	parser.add_option("-l", "--linear", dest="linear", action="store_true", help="If true, disable multiprocessing.")
	parser.add_option("-n", "--name", dest="name", help="The name of the output file, defaults to directory name of ntuples.", default="")
	parser.add_option("-t", "--treename", dest="treename", help="The name of the ", default="tree-" + version)
	(opts, args) = parser.parse_args()
	
	# Load plugins.
	plugins.loadPlugins([], True)

	# Run the treemaker over all provided directories.
	for arg in args:
		directory = os.path.abspath(arg)
		if not os.path.exists(directory):
			print "Error: no such directory: " + arg
			sys.exit(1)
		core.runTreemaker(directory, opts.treename, opts.data, opts.force, opts.name, opts.linear)

if __name__ == '__main__':
	main()
