#!/usr/bin/env python

# Python standard library.
import array
import multiprocessing
import optparse
import os
import shutil
import sys

# Our own libraries.
from Treemaker.Treemaker import config
from Treemaker.Treemaker import core
from Treemaker.Treemaker import parser

def main():
	treeParser = parser.getCLIParser()
	(opts, args) = treeParser.parse_args()
	
	# The only positional argument treemaker v3 takes is config file.
	for arg in args:
		treemakerConfig = config.TreemakerConfig(arg)


		core.runTreemaker(treemakerConfig)
	
	# Old code.
	
	# Attempt to load plugins from plugin config file.
	#core.loadPlugins(opts.config)

	# Run the treemaker over all provided directories.
	#for arg in args:
	#	directory = os.path.abspath(arg)
	#	if not os.path.exists(directory):
	#		print "Error: no such directory: " + arg
	#		sys.exit(1)
	#	core.runTreemaker(directory, opts.treename, opts.data, opts.force, opts.name, opts.linear)

if __name__ == '__main__':
	main()
